auth
Dmitriy-sem/fork-nestjs pull request #1
Opened 2021-08-02 14:40 UTC by Dmitriy-sem

2021-08-02 14:57 UTC, Nivolves requested changes

2021-08-02 14:57 UTC, Nivolves commented on src/app.module.ts
> +    MongooseModule.forRoot('mongodb+srv://dbDmitriy:4!U_x$TukpTs2iC@cluster0.jrou0.mongodb.net/fork?retryWrites=true&w=majority'),
use сonfigModule and move mongo uri to .env

2021-08-02 14:57 UTC, Nivolves commented on src/auth/auth.controller.ts
> +        const {username, password, email} = newUserDto
Move all logic to service. In controller u should only call method from service.

2021-08-02 14:57 UTC, Nivolves commented on src/auth/auth.controller.ts
> +        private AuthService: AuthService,
```suggestion
        private authService: AuthService,
```

2021-08-02 14:57 UTC, Nivolves commented on src/auth/auth.controller.ts
> +        } return 'User with this username is already exists'
U should ```  throw new HttpException('User with this username is already exists', HttpStatus.BAD_REQUEST);```  instead of returning text

2021-08-02 14:57 UTC, Nivolves commented on src/auth/auth.controller.ts
> +    async register(@Body() newUserDto: CreateUserDto){
type the response, pls

2021-08-02 14:57 UTC, Nivolves commented on src/auth/auth.service.ts
> +    async createUser(data: CreateUserDto){
Move all logic with users to separate module

2021-08-02 14:57 UTC, Nivolves commented on src/auth/dto/create-user.dto.ts
> +export class CreateUserDto {
validate it with ```class-validator``` and ```class-transformer```

2021-08-02 14:57 UTC, Nivolves commented on src/auth/dto/create-user.dto.ts
> +export class CreateUserDto {
Add swagger for it

2021-08-02 14:57 UTC, Nivolves commented on src/auth/schemas/user.schema.ts
> +    @Prop()
```suggestion
    @Prop({type: String, required: true, unique: true})
```

2021-08-02 14:57 UTC, Nivolves commented on src/auth/schemas/user.schema.ts
> +    @Prop()
suggestion above is for properties in schema

2021-08-03 09:19 UTC, Dmitriy-sem commented on src/auth/auth.service.ts
> +    async createUser(data: CreateUserDto){
должно быть два модуля юзер и ауз? Если да, то что получается регистрация(создание юзера) должна быть в юзер контроллер, а авторизация в ауз контролере. Я правильно понимаю?

2021-10-21 13:48 UTC, closed without merging